### ISSUE TITLE
[ISSUE SAMPLE] [High Risk] Contract Verify with a *Global* WitnessScope

### ISSUE THREAD

**Issue by overlordsecurity** [neocompounder/cneo-contract#1]
## Fact

By allowing everyone call the method `compound` with this contract's permission in `verify`, cNEO aims to give the user's transaction a witness. 

> the first code piece is the verify method, the second is the `compound` method where cNEO can call `account`'s code

https://github.com/neocompounder/cneo-contract/blob/a90710104f38773ac6945ac13571696e45322bf0/src/main/java/com/neocompounder/cneo/CompoundingNeo.java#L153-L164
https://github.com/neocompounder/cneo-contract/blob/a90710104f38773ac6945ac13571696e45322bf0/src/main/java/com/neocompounder/cneo/CompoundingNeo.java#L450-L453

## Risk

It is very dangerous to have a `verify` method in NEO contract unless contract can do a very careful check. If someone send a transaction and list cNEO a second witness and set the witness scope to `Global`, he can do anything in `compound`'s call to the `account` including transfer all the cNEO's NEP-17 tokens to him.

## Recommendation: 

[TODO]

## code audit invitation

We are overlord, mainly focused on NEO3 and other public chains. Overlord consists of a group of anonymous developers and researchers who are experts in the cybersecurity and blockchain especially on NEO3. You can find our clients [here](https://overlord.wtf/).

**Comment by jseagrave21** [comment]
@lyrebird-finance is this still a concern? I saw the Red4Sec audit but this issue is still open.

**Comment by lyrebird-finance** [comment]
> @lyrebird-finance is this still a concern? I saw the Red4Sec audit but this issue is still open.

This is no longer applicable. The code has been changed since to completely preclude the need for a `verify` method altogether.
